using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoHttpClient;

[Generator]
public sealed class AutoHttpClientGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated by AutoHttpClient.Generator/>
#nullable enable
using System;

namespace AutoHttpClient
{
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    public sealed class HttpClientAttribute : Attribute
    {
        /// <summary>Optional base address applied to the HttpClient.</summary>
        public string? BaseAddress { get; set; }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class GetAttribute : Attribute
    {
        public string Template { get; }
        public GetAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PostAttribute : Attribute
    {
        public string Template { get; }
        public PostAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PutAttribute : Attribute
    {
        public string Template { get; }
        public PutAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class DeleteAttribute : Attribute
    {
        public string Template { get; }
        public DeleteAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class PatchAttribute : Attribute
    {
        public string Template { get; }
        public PatchAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class BodyAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class QueryAttribute : Attribute
    {
        public string? Name { get; }
        public QueryAttribute(string? name = null) => Name = name;
    }

    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    public sealed class HeaderAttribute : Attribute
    {
        public string Name { get; }
        public HeaderAttribute(string name) => Name = name;
    }
}
";

    private static readonly DiagnosticDescriptor AH001 = new(
        id: "AH001",
        title: "HTTP method attribute missing",
        messageFormat: "Method '{0}' on [HttpClient] interface '{1}' has no HTTP method attribute ([Get], [Post], etc.) — it will not be generated",
        category: "AutoHttpClient",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AH002 = new(
        id: "AH002",
        title: "Route template parameter missing method parameter",
        messageFormat: "Route template parameter '{0}' in '{1}' on '{2}' has no matching method parameter",
        category: "AutoHttpClient",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AH003 = new(
        id: "AH003",
        title: "Multiple [Body] parameters",
        messageFormat: "Method '{0}' on '{1}' has multiple [Body] parameters — only one is allowed",
        category: "AutoHttpClient",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoHttpClient.Attributes.g.cs", AttributeSource));

        var interfaces = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoHttpClient.HttpClientAttribute",
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, ct) => TransformInterface(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(interfaces.Collect(), static (ctx, items) => Generate(ctx, items));
    }

    private static HttpClientInterfaceInfo? TransformInterface(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol interfaceSymbol)
        {
            return null;
        }

        var info = new HttpClientInterfaceInfo
        {
            InterfaceName = interfaceSymbol.Name,
            InterfaceTypeFqn = ToFullyQualified(interfaceSymbol),
            InterfaceDisplayName = interfaceSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Namespace = GetNamespace(interfaceSymbol),
            ImplementationName = GetImplementationName(interfaceSymbol.Name),
            BaseAddress = ReadBaseAddress(context.Attributes),
        };

        var cancellationTokenType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Threading.CancellationToken");
        var httpResponseMessageType = context.SemanticModel.Compilation.GetTypeByMetadataName("System.Net.Http.HttpResponseMessage");

        foreach (var method in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (method.MethodKind != MethodKind.Ordinary)
            {
                continue;
            }

            var methodResult = AnalyzeMethod(method, info.InterfaceDisplayName, cancellationTokenType, httpResponseMessageType);
            info.Diagnostics.AddRange(methodResult.Diagnostics);

            if (methodResult.Method is null)
            {
                info.CanGenerate = false;
                continue;
            }

            info.Methods.Add(methodResult.Method);
        }

        if (info.Methods.Count == 0)
        {
            info.CanGenerate = false;
        }

        return info;
    }

    private static MethodAnalysisResult AnalyzeMethod(
        IMethodSymbol method,
        string interfaceDisplayName,
        INamedTypeSymbol? cancellationTokenType,
        INamedTypeSymbol? httpResponseMessageType)
    {
        var diagnostics = new List<PendingDiagnostic>();
        var location = method.Locations.FirstOrDefault() ?? Location.None;

        if (!TryGetHttpMethod(method, out var verb, out var template))
        {
            diagnostics.Add(new PendingDiagnostic(AH001, location, method.Name, interfaceDisplayName));
            return new MethodAnalysisResult(null, diagnostics);
        }

        var routeTokens = ParseRouteTokens(template!);
        foreach (var routeToken in routeTokens)
        {
            if (!method.Parameters.Any(p => string.Equals(p.Name, routeToken, StringComparison.OrdinalIgnoreCase)))
            {
                diagnostics.Add(new PendingDiagnostic(AH002, location, routeToken, method.Name, interfaceDisplayName));
                return new MethodAnalysisResult(null, diagnostics);
            }
        }

        if (!TryGetReturnInfo(method.ReturnType, httpResponseMessageType, out var returnHandling, out var returnTypeFqn, out var jsonResultTypeFqn, out var jsonResultNullable))
        {
            return new MethodAnalysisResult(null, diagnostics);
        }

        var parameters = new List<MethodParameterInfo>();
        var bodyParameters = new List<MethodParameterInfo>();
        var routeSet = new HashSet<string>(routeTokens, StringComparer.OrdinalIgnoreCase);

        foreach (var parameter in method.Parameters)
        {
            if (cancellationTokenType is not null && SymbolEqualityComparer.Default.Equals(parameter.Type, cancellationTokenType))
            {
                parameters.Add(new MethodParameterInfo
                {
                    Name = parameter.Name,
                    TypeFqn = ToFullyQualified(parameter.Type),
                    Kind = ParameterKind.CancellationToken,
                    IsOptional = parameter.IsOptional,
                });
                continue;
            }

            var parameterInfo = new MethodParameterInfo
            {
                Name = parameter.Name,
                TypeFqn = ToFullyQualified(parameter.Type),
                IsOptional = parameter.IsOptional,
                IsNullable = IsNullable(parameter.Type),
            };

            if (HasAttribute(parameter, "AutoHttpClient.BodyAttribute"))
            {
                parameterInfo.Kind = ParameterKind.Body;
                bodyParameters.Add(parameterInfo);
            }
            else if (TryGetQueryName(parameter, out var queryName))
            {
                parameterInfo.Kind = ParameterKind.Query;
                parameterInfo.QueryName = queryName;
            }
            else if (TryGetHeaderName(parameter, out var headerName))
            {
                parameterInfo.Kind = ParameterKind.Header;
                parameterInfo.HeaderName = headerName;
            }
            else if (routeSet.Contains(parameter.Name))
            {
                parameterInfo.Kind = ParameterKind.Route;
            }
            else
            {
                parameterInfo.Kind = ParameterKind.Query;
                parameterInfo.QueryName = parameter.Name;
            }

            parameters.Add(parameterInfo);
        }

        if (bodyParameters.Count > 1)
        {
            diagnostics.Add(new PendingDiagnostic(AH003, location, method.Name, interfaceDisplayName));
            return new MethodAnalysisResult(null, diagnostics);
        }

        return new MethodAnalysisResult(
            new HttpMethodInfo
            {
                Name = method.Name,
                ReturnTypeFqn = returnTypeFqn,
                Verb = verb,
                Template = template!,
                ReturnHandling = returnHandling,
                JsonResultTypeFqn = jsonResultTypeFqn,
                JsonResultNullable = jsonResultNullable,
                Parameters = parameters,
            },
            diagnostics);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<HttpClientInterfaceInfo> interfaces)
    {
        if (interfaces.IsDefaultOrEmpty)
        {
            return;
        }

        var generated = new List<HttpClientInterfaceInfo>();

        foreach (var info in interfaces.OrderBy(static x => x.InterfaceTypeFqn, StringComparer.Ordinal))
        {
            foreach (var diagnostic in info.Diagnostics)
            {
                context.ReportDiagnostic(Diagnostic.Create(diagnostic.Descriptor, diagnostic.Location, diagnostic.Args));
            }

            if (!info.CanGenerate || info.Methods.Count == 0)
            {
                continue;
            }

            context.AddSource($"{info.InterfaceName}.AutoHttpClient.g.cs", GenerateClientSource(info));
            generated.Add(info);
        }

        if (generated.Count > 0)
        {
            context.AddSource("AutoHttpClientRegistrations.g.cs", GenerateRegistrationSource(generated));
        }
    }

    private static string GenerateClientSource(HttpClientInterfaceInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoHttpClient.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.Append("namespace ").Append(info.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(info.Namespace) ? string.Empty : "    ";
        sb.Append(indent).Append("internal sealed class ").Append(info.ImplementationName).Append(" : ").Append(info.InterfaceTypeFqn).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private readonly global::System.Net.Http.HttpClient _httpClient;");
        sb.Append(indent).AppendLine("    private readonly global::System.Text.Json.JsonSerializerOptions _jsonOptions;");
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(info.ImplementationName).AppendLine("(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions? jsonOptions = null)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        _httpClient = httpClient;");
        sb.Append(indent).AppendLine("        _jsonOptions = jsonOptions ?? global::System.Text.Json.JsonSerializerOptions.Web;");
        sb.Append(indent).AppendLine("    }");

        foreach (var method in info.Methods)
        {
            sb.AppendLine();
            sb.Append(indent).Append("    public async ").Append(method.ReturnTypeFqn).Append(' ').Append(method.Name).Append('(').Append(BuildParameterList(method.Parameters)).AppendLine(")");
            sb.Append(indent).AppendLine("    {");

            var routeBindings = method.Parameters
                .Where(static p => p.Kind == ParameterKind.Route)
                .ToDictionary(static p => p.Name, static p => p.Name, StringComparer.OrdinalIgnoreCase);
            var queryParameters = method.Parameters.Where(static p => p.Kind == ParameterKind.Query).ToArray();
            var headerParameters = method.Parameters.Where(static p => p.Kind == ParameterKind.Header).ToArray();
            var bodyParameter = method.Parameters.FirstOrDefault(static p => p.Kind == ParameterKind.Body);
            var ctArgument = GetCancellationTokenArgument(method.Parameters);
            var useRequestMessage = headerParameters.Length > 0 || RequiresRequestMessage(method.Verb, bodyParameter is not null);

            sb.Append(indent).Append("        var __url = ").Append(ToInterpolatedUrlLiteral(method.Template, routeBindings)).AppendLine(";");

            if (queryParameters.Length > 0)
            {
                sb.Append(indent).AppendLine("        var __query = new global::System.Text.StringBuilder();");
                foreach (var parameter in queryParameters)
                {
                    if (parameter.IsNullable)
                    {
                        sb.Append(indent).Append("        if (").Append(parameter.Name).AppendLine(" != null)");
                        sb.Append(indent).AppendLine("        {");
                        AppendQueryAppendLines(sb, indent + "            ", parameter);
                        sb.Append(indent).AppendLine("        }");
                    }
                    else
                    {
                        AppendQueryAppendLines(sb, indent + "        ", parameter);
                    }
                }

                sb.Append(indent).AppendLine("        if (__query.Length > 0)");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine("            __url += \"?\" + __query.ToString();");
                sb.Append(indent).AppendLine("        }");
            }

            if (useRequestMessage)
            {
                sb.Append(indent).Append("        using var __request = new global::System.Net.Http.HttpRequestMessage(").Append(GetHttpMethodExpression(method.Verb)).AppendLine(", __url);");
                if (bodyParameter is not null)
                {
                    sb.Append(indent).Append("        __request.Content = global::System.Net.Http.Json.JsonContent.Create(").Append(bodyParameter.Name).AppendLine(", options: _jsonOptions);");
                }

                foreach (var parameter in headerParameters)
                {
                    if (parameter.IsNullable)
                    {
                        sb.Append(indent).Append("        if (").Append(parameter.Name).AppendLine(" != null)");
                        sb.Append(indent).AppendLine("        {");
                        AppendHeaderAppendLine(sb, indent + "            ", parameter);
                        sb.Append(indent).AppendLine("        }");
                    }
                    else
                    {
                        AppendHeaderAppendLine(sb, indent + "        ", parameter);
                    }
                }

                sb.Append(indent).Append("        var __response = await _httpClient.SendAsync(__request, ").Append(ctArgument).AppendLine(").ConfigureAwait(false);");
            }
            else
            {
                sb.Append(indent).Append("        var __response = await ").Append(GetDirectCall(method, bodyParameter, ctArgument)).AppendLine(".ConfigureAwait(false);");
            }

            AppendReturnHandling(sb, indent, method, ctArgument);
            sb.Append(indent).AppendLine("    }");
        }

        sb.Append(indent).AppendLine("}");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateRegistrationSource(IReadOnlyList<HttpClientInterfaceInfo> interfaces)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoHttpClient.Generator/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("public static class AutoHttpClientExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddAutoHttpClients(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var info in interfaces.OrderBy(static x => x.InterfaceTypeFqn, StringComparer.Ordinal))
        {
            var implementationFqn = string.IsNullOrEmpty(info.Namespace)
                ? $"global::{info.ImplementationName}"
                : $"global::{info.Namespace}.{info.ImplementationName}";

            if (string.IsNullOrWhiteSpace(info.BaseAddress))
            {
                sb.Append("        global::Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient<")
                    .Append(info.InterfaceTypeFqn)
                    .Append(", ")
                    .Append(implementationFqn)
                    .AppendLine(">(services);");
            }
            else
            {
                sb.Append("        global::Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient<")
                    .Append(info.InterfaceTypeFqn)
                    .Append(", ")
                    .Append(implementationFqn)
                    .AppendLine(">(services, static client =>");
                sb.AppendLine("        {");
                sb.Append("            client.BaseAddress = new global::System.Uri(")
                    .Append(ToCSharpStringLiteral(info.BaseAddress!))
                    .AppendLine(");");
                sb.AppendLine("        });");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendReturnHandling(StringBuilder sb, string indent, HttpMethodInfo method, string ctArgument)
    {
        switch (method.ReturnHandling)
        {
            case ReturnHandlingKind.None:
                sb.Append(indent).AppendLine("        __response.EnsureSuccessStatusCode();");
                break;
            case ReturnHandlingKind.Response:
                sb.Append(indent).AppendLine("        return __response;");
                break;
            default:
                sb.Append(indent).AppendLine("        __response.EnsureSuccessStatusCode();");
                if (method.JsonResultNullable)
                {
                    sb.Append(indent)
                        .Append("        return await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<")
                        .Append(method.JsonResultTypeFqn)
                        .Append(">(__response.Content, _jsonOptions, ")
                        .Append(ctArgument)
                        .AppendLine(").ConfigureAwait(false);");
                }
                else
                {
                    sb.Append(indent)
                        .Append("        return (await global::System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync<")
                        .Append(method.JsonResultTypeFqn)
                        .Append(">(__response.Content, _jsonOptions, ")
                        .Append(ctArgument)
                        .AppendLine(").ConfigureAwait(false))!;");
                }

                break;
        }
    }

    private static void AppendQueryAppendLines(StringBuilder sb, string indent, MethodParameterInfo parameter)
    {
        sb.Append(indent).AppendLine("if (__query.Length > 0) __query.Append('&');");
        sb.Append(indent)
            .Append("__query.Append(")
            .Append(ToCSharpStringLiteral(parameter.QueryName ?? parameter.Name))
            .AppendLine(").Append(\"=\").Append(global::System.Uri.EscapeDataString(" + parameter.Name + ".ToString()!));");
    }

    private static void AppendHeaderAppendLine(StringBuilder sb, string indent, MethodParameterInfo parameter)
    {
        sb.Append(indent)
            .Append("__request.Headers.TryAddWithoutValidation(")
            .Append(ToCSharpStringLiteral(parameter.HeaderName ?? parameter.Name))
            .Append(", ")
            .Append(parameter.Name)
            .AppendLine(".ToString()!);");
    }

    private static string GetDirectCall(HttpMethodInfo method, MethodParameterInfo? bodyParameter, string ctArgument)
    {
        return method.Verb switch
        {
            HttpVerb.Get => $"_httpClient.GetAsync(__url, {ctArgument})",
            HttpVerb.Delete when bodyParameter is null => $"_httpClient.DeleteAsync(__url, {ctArgument})",
            HttpVerb.Post when bodyParameter is not null => $"global::System.Net.Http.Json.HttpClientJsonExtensions.PostAsJsonAsync(_httpClient, __url, {bodyParameter.Name}, _jsonOptions, {ctArgument})",
            HttpVerb.Put when bodyParameter is not null => $"global::System.Net.Http.Json.HttpClientJsonExtensions.PutAsJsonAsync(_httpClient, __url, {bodyParameter.Name}, _jsonOptions, {ctArgument})",
            HttpVerb.Patch when bodyParameter is not null => $"global::System.Net.Http.Json.HttpClientJsonExtensions.PatchAsJsonAsync(_httpClient, __url, {bodyParameter.Name}, _jsonOptions, {ctArgument})",
            _ => throw new InvalidOperationException("Method requires HttpRequestMessage generation."),
        };
    }

    private static bool RequiresRequestMessage(HttpVerb verb, bool hasBody)
        => verb switch
        {
            HttpVerb.Get => hasBody,
            HttpVerb.Delete => hasBody,
            HttpVerb.Post => !hasBody,
            HttpVerb.Put => !hasBody,
            HttpVerb.Patch => !hasBody,
            _ => true,
        };

    private static string GetHttpMethodExpression(HttpVerb verb)
        => verb switch
        {
            HttpVerb.Get => "global::System.Net.Http.HttpMethod.Get",
            HttpVerb.Post => "global::System.Net.Http.HttpMethod.Post",
            HttpVerb.Put => "global::System.Net.Http.HttpMethod.Put",
            HttpVerb.Delete => "global::System.Net.Http.HttpMethod.Delete",
            HttpVerb.Patch => "global::System.Net.Http.HttpMethod.Patch",
            _ => "global::System.Net.Http.HttpMethod.Get",
        };

    private static string GetCancellationTokenArgument(IReadOnlyList<MethodParameterInfo> parameters)
        => parameters.FirstOrDefault(static p => p.Kind == ParameterKind.CancellationToken)?.Name
            ?? "global::System.Threading.CancellationToken.None";

    private static string BuildParameterList(IReadOnlyList<MethodParameterInfo> parameters)
        => string.Join(", ", parameters.Select(static p => p.TypeFqn + " " + p.Name + (p.IsOptional ? " = default" : string.Empty)));

    private static bool TryGetReturnInfo(
        ITypeSymbol returnType,
        INamedTypeSymbol? httpResponseMessageType,
        out ReturnHandlingKind returnHandling,
        out string returnTypeFqn,
        out string? jsonResultTypeFqn,
        out bool jsonResultNullable)
    {
        returnTypeFqn = ToFullyQualified(returnType);
        jsonResultTypeFqn = null;
        jsonResultNullable = false;

        if (returnType is not INamedTypeSymbol namedType || namedType.Name != "Task" || namedType.ContainingNamespace.ToDisplayString() != "System.Threading.Tasks")
        {
            returnHandling = ReturnHandlingKind.None;
            return false;
        }

        if (!namedType.IsGenericType)
        {
            returnHandling = ReturnHandlingKind.None;
            return true;
        }

        var resultType = namedType.TypeArguments[0];
        if (httpResponseMessageType is not null && SymbolEqualityComparer.Default.Equals(resultType, httpResponseMessageType))
        {
            returnHandling = ReturnHandlingKind.Response;
            return true;
        }

        returnHandling = ReturnHandlingKind.Json;
        jsonResultTypeFqn = ToFullyQualified(resultType);
        jsonResultNullable = IsNullable(resultType);
        return true;
    }

    private static bool TryGetHttpMethod(IMethodSymbol method, out HttpVerb verb, out string? template)
    {
        foreach (var attribute in method.GetAttributes())
        {
            var metadataName = attribute.AttributeClass?.ToDisplayString();
            switch (metadataName)
            {
                case "AutoHttpClient.GetAttribute":
                    verb = HttpVerb.Get;
                    template = attribute.ConstructorArguments[0].Value as string;
                    return true;
                case "AutoHttpClient.PostAttribute":
                    verb = HttpVerb.Post;
                    template = attribute.ConstructorArguments[0].Value as string;
                    return true;
                case "AutoHttpClient.PutAttribute":
                    verb = HttpVerb.Put;
                    template = attribute.ConstructorArguments[0].Value as string;
                    return true;
                case "AutoHttpClient.DeleteAttribute":
                    verb = HttpVerb.Delete;
                    template = attribute.ConstructorArguments[0].Value as string;
                    return true;
                case "AutoHttpClient.PatchAttribute":
                    verb = HttpVerb.Patch;
                    template = attribute.ConstructorArguments[0].Value as string;
                    return true;
            }
        }

        verb = default;
        template = null;
        return false;
    }

    private static bool TryGetQueryName(IParameterSymbol parameter, out string? name)
    {
        foreach (var attribute in parameter.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "AutoHttpClient.QueryAttribute")
            {
                continue;
            }

            name = attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string value
                ? value
                : parameter.Name;
            name ??= parameter.Name;
            return true;
        }

        name = null;
        return false;
    }

    private static bool TryGetHeaderName(IParameterSymbol parameter, out string? name)
    {
        foreach (var attribute in parameter.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "AutoHttpClient.HeaderAttribute")
            {
                continue;
            }

            name = attribute.ConstructorArguments[0].Value as string ?? parameter.Name;
            return true;
        }

        name = null;
        return false;
    }

    private static bool HasAttribute(IParameterSymbol parameter, string metadataName)
        => parameter.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == metadataName);

    private static string? ReadBaseAddress(ImmutableArray<AttributeData> attributes)
    {
        foreach (var attribute in attributes)
        {
            if (attribute.AttributeClass?.ToDisplayString() != "AutoHttpClient.HttpClientAttribute")
            {
                continue;
            }

            foreach (var namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == "BaseAddress")
                {
                    return namedArgument.Value.Value as string;
                }
            }
        }

        return null;
    }

    private static string GetImplementationName(string interfaceName)
    {
        if (interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1]))
        {
            return interfaceName.Substring(1) + "Client";
        }

        return interfaceName + "Client";
    }

    private static string GetNamespace(INamedTypeSymbol symbol)
        => symbol.ContainingNamespace is { IsGlobalNamespace: false } ns ? ns.ToDisplayString() : string.Empty;

    private static string ToFullyQualified(ITypeSymbol symbol)
        => symbol.ToDisplayString(FullyQualifiedFormat);

    private static bool IsNullable(ITypeSymbol symbol)
    {
        if (symbol.NullableAnnotation == NullableAnnotation.Annotated)
        {
            return true;
        }

        return symbol is INamedTypeSymbol namedType && namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
    }

    private static List<string> ParseRouteTokens(string template)
    {
        var tokens = new List<string>();
        var index = 0;
        while (index < template.Length)
        {
            var open = template.IndexOf('{', index);
            if (open < 0)
            {
                break;
            }

            var close = template.IndexOf('}', open + 1);
            if (close < 0)
            {
                break;
            }

            var token = template.Substring(open + 1, close - open - 1).Trim();
            if (token.Length > 0)
            {
                tokens.Add(token);
            }

            index = close + 1;
        }

        return tokens;
    }

    private static string ToInterpolatedUrlLiteral(string template, IReadOnlyDictionary<string, string> routeBindings)
    {
        var sb = new StringBuilder();
        var index = 0;
        var hasInterpolation = false;

        while (index < template.Length)
        {
            var open = template.IndexOf('{', index);
            if (open < 0)
            {
                sb.Append(EscapeInterpolatedLiteral(template.Substring(index)));
                break;
            }

            var close = template.IndexOf('}', open + 1);
            if (close < 0)
            {
                sb.Append(EscapeInterpolatedLiteral(template.Substring(index)));
                break;
            }

            sb.Append(EscapeInterpolatedLiteral(template.Substring(index, open - index)));
            var token = template.Substring(open + 1, close - open - 1);
            if (routeBindings.TryGetValue(token, out var parameterName))
            {
                sb.Append('{').Append(parameterName).Append('}');
                hasInterpolation = true;
            }
            else
            {
                sb.Append(EscapeInterpolatedLiteral(template.Substring(open, close - open + 1)));
            }

            index = close + 1;
        }

        return hasInterpolation
            ? "$\"" + sb + "\""
            : "\"" + sb + "\"";
    }

    private static string EscapeInterpolatedLiteral(string value)
        => value.Replace("{", "{{")
            .Replace("}", "}}")
            .Replace("\"", "\\\"");

    private static string ToCSharpStringLiteral(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private readonly struct PendingDiagnostic
    {
        public PendingDiagnostic(DiagnosticDescriptor descriptor, Location location, params object[] args)
        {
            Descriptor = descriptor;
            Location = location;
            Args = args;
        }

        public DiagnosticDescriptor Descriptor { get; }
        public Location Location { get; }
        public object[] Args { get; }
    }

    private sealed class MethodAnalysisResult
    {
        public MethodAnalysisResult(HttpMethodInfo? method, List<PendingDiagnostic> diagnostics)
        {
            Method = method;
            Diagnostics = diagnostics;
        }

        public HttpMethodInfo? Method { get; }
        public List<PendingDiagnostic> Diagnostics { get; }
    }

    private sealed class HttpClientInterfaceInfo
    {
        public string InterfaceName { get; set; } = string.Empty;
        public string InterfaceTypeFqn { get; set; } = string.Empty;
        public string InterfaceDisplayName { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
        public string ImplementationName { get; set; } = string.Empty;
        public string? BaseAddress { get; set; }
        public bool CanGenerate { get; set; } = true;
        public List<HttpMethodInfo> Methods { get; } = new();
        public List<PendingDiagnostic> Diagnostics { get; } = new();
    }

    private sealed class HttpMethodInfo
    {
        public string Name { get; set; } = string.Empty;
        public string ReturnTypeFqn { get; set; } = string.Empty;
        public HttpVerb Verb { get; set; }
        public string Template { get; set; } = string.Empty;
        public ReturnHandlingKind ReturnHandling { get; set; }
        public string? JsonResultTypeFqn { get; set; }
        public bool JsonResultNullable { get; set; }
        public IReadOnlyList<MethodParameterInfo> Parameters { get; set; } = Array.Empty<MethodParameterInfo>();
    }

    private sealed class MethodParameterInfo
    {
        public string Name { get; set; } = string.Empty;
        public string TypeFqn { get; set; } = string.Empty;
        public ParameterKind Kind { get; set; }
        public string? QueryName { get; set; }
        public string? HeaderName { get; set; }
        public bool IsOptional { get; set; }
        public bool IsNullable { get; set; }
    }

    private enum HttpVerb
    {
        Get,
        Post,
        Put,
        Delete,
        Patch,
    }

    private enum ParameterKind
    {
        Route,
        Query,
        Header,
        Body,
        CancellationToken,
    }

    private enum ReturnHandlingKind
    {
        None,
        Json,
        Response,
    }
}
