using AutoHttpClient.OpenApiScaffold;
using Xunit;

namespace AutoHttpClient.OpenApiScaffold.Tests;

public class OpenApiInterfaceScaffolderTests
{
    private const string SampleOpenApi = """
        {
          "openapi": "3.0.1",
          "info": {
            "title": "Pet Store",
            "version": "1.0.0"
          },
          "servers": [
            {
              "url": "https://api.example.com"
            }
          ],
          "paths": {
            "/pets": {
              "get": {
                "operationId": "listPets",
                "parameters": [
                  {
                    "name": "status",
                    "in": "query",
                    "required": false,
                    "schema": {
                      "type": "string"
                    }
                  }
                ],
                "responses": {
                  "200": {
                    "description": "OK",
                    "content": {
                      "application/json": {
                        "schema": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/Pet"
                          }
                        }
                      }
                    }
                  }
                }
              },
              "post": {
                "operationId": "createPet",
                "requestBody": {
                  "required": true,
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/CreatePetRequest"
                      }
                    }
                  }
                },
                "responses": {
                  "201": {
                    "description": "Created",
                    "content": {
                      "application/json": {
                        "schema": {
                          "$ref": "#/components/schemas/Pet"
                        }
                      }
                    }
                  }
                }
              }
            },
            "/pets/{petId}": {
              "get": {
                "operationId": "getPet",
                "parameters": [
                  {
                    "name": "petId",
                    "in": "path",
                    "required": true,
                    "schema": {
                      "type": "integer",
                      "format": "int32"
                    }
                  }
                ],
                "responses": {
                  "200": {
                    "description": "OK",
                    "content": {
                      "application/json": {
                        "schema": {
                          "$ref": "#/components/schemas/Pet"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "components": {
            "schemas": {
              "Pet": {
                "type": "object"
              },
              "CreatePetRequest": {
                "type": "object"
              }
            }
          }
        }
        """;

    [Fact]
    public void Scaffold_ProducesExpectedInterface()
    {
        var scaffolder = new OpenApiInterfaceScaffolder();

        var result = scaffolder.Scaffold(
            SampleOpenApi,
            new ScaffoldOptions
            {
                InterfaceName = "IPetStoreApi",
                Namespace = "Demo.Clients",
                SourceName = "petstore.json",
            });

        Assert.True(result.Success, result.ErrorMessage);
        Assert.Equal(
            Normalize(
                """
                // <auto-generated by AutoHttpClient.OpenApiScaffold/>
                #nullable enable
                using System;
                using System.Collections.Generic;
                using System.Text.Json;
                using System.Threading;
                using System.Threading.Tasks;
                using AutoHttpClient;

                namespace Demo.Clients
                {

                    [HttpClient(BaseAddress = "https://api.example.com")]
                    public partial interface IPetStoreApi
                    {
                        [Get("/pets")]
                        Task<List<Pet>> ListPetsAsync([Query("status")] string? status = default, CancellationToken ct = default);

                        [Post("/pets")]
                        Task<Pet> CreatePetAsync([Body] CreatePetRequest createPetRequest, CancellationToken ct = default);

                        [Get("/pets/{petId}")]
                        Task<Pet> GetPetAsync(int petId, CancellationToken ct = default);
                    }

                }
                """),
            Normalize(result.Output!));
    }

    [Theory]
    [InlineData("")]
    [InlineData("{\"openapi\":\"3.0.1\",\"paths\":}")]
    public void Scaffold_InvalidDocument_ReturnsClearError(string input)
    {
        var scaffolder = new OpenApiInterfaceScaffolder();

        var result = scaffolder.Scaffold(input, new ScaffoldOptions { SourceName = "broken.json" });

        Assert.False(result.Success);
        Assert.NotNull(result.ErrorMessage);
        Assert.Contains("OpenAPI document", result.ErrorMessage);
    }

    private static string Normalize(string value)
        => value.Replace("\r\n", "\n").Trim();
}
